[graph]
targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
]

all-features = true

[licenses]
version = 2
private = { ignore = true }
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "BSD-3-Clause",
    "EUPL-1.2",
    "ISC",
    "OpenSSL",
    "Zlib",
    "CDLA-Permissive-2.0",
    "BSD-2-Clause",
    "CC0-1.0",
    "Apache-2.0 WITH LLVM-exception"
]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
deny = [
    { crate = "openssl", use-instead = "rustls" },
    { crate = "openssl-sys", use-instead = "rustls" },
    { crate = "ring", use-instead = "aws-lc-sys"}
]
multiple-versions = "allow"

[advisories]
ignore = [
    { id = "RUSTSEC-2024-0320", reason = "yaml-rust is transitively used by Typst, see https://github.com/trishume/syntect/issues/537" },
    { id = "RUSTSEC-2024-0436", reason = "paste is used by Typst, see https://github.com/typst/biblatex/issues/87" }
]
