services:
  db:
    image: ghcr.io/tweedegolf/postgres:18
    environment:
      POSTGRES_USER: kiesraad
      POSTGRES_DB: kiesraad
      TZ: Europe/Amsterdam
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: [ "127.0.0.1:5432:5432" ]
    volumes:
      - database-data:/var/lib/postgresql/

volumes:
  database-data:
