apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eks-tls-cert
  namespace: ingress
spec:
  secretName: eks-tls-cert
  issuerRef:
    name: letsencrypt-production-dns
    kind: ClusterIssuer
  dnsNames:
    - "*.eks-test.nl"
