extraArgs:
  provider: github
  set-xauthrequest: "true"
  pass-authorization-header: "true"
  github-org: kiesraad

# Oauth client configuration specifics
config:
  # Add config annotations
  annotations: {}
  # OAuth client ID
  clientID: "XXXXXXXXX"
  # OAuth client secret
  clientSecret: "XXXXXXXXXXX"
  # Create a new secret with the following command
  # openssl rand -base64 32 | head -c 32 | base64
  # Use an existing secret for OAuth2 credentials (see secret.yaml for required fields)
  # Example:
  # existingSecret: secret
  cookieSecret: "XXXXXXXXXXX"
  # The name of the cookie that oauth2-proxy will create
  # If left empty, it will default to the release name
  cookieName: "SESSION"

metrics:
  enabled: false
