apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`^.+\.eks-test\.nl$`) && PathPrefix(`/oauth2`)
      kind: Rule
      services:
        - name: oauth2-proxy
          port: http
  # This falls back to the default certificate, which should be a wildcard cert for *.eks-test.nl
  tls: {}
