apiVersion: v1
kind: Service
metadata:
  name: bag-lookup
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: bag-lookup
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
