apiVersion: apps/v1
kind: Deployment
metadata:
  name: bag-lookup
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: bag-lookup
    app.kubernetes.io/part-of: eks
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: bag
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bag-lookup
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bag-lookup
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:
      containers:
        - name: bag-lookup
          image: "ghcr.io/tweedegolf/bag-address-lookup:latest"
          ports:
            - containerPort: 8080
              name: http
