{{ if .Values.db.erase }}
apiVersion: batch/v1
kind: Job
metadata:
  name: erase-database-hook
  labels:
    app.kubernetes.io/name: erase-db
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: test-deployment
  annotations:
    "helm.sh/hook": post-delete,pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: erase-db
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: test-deployment
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: erase-db
          image: "ghcr.io/kiesraad/e-ks/db:{{ .Chart.AppVersion }}"
          command:
            - dropdb
            - {{ .Values.subdomain }}
            - --force
          env:
            - name: PGHOST
              value: {{ .Values.db.host | quote }}
            - name: PGPORT
              value: {{ .Values.db.port | quote }}
            - name: PGUSER
              value: {{ .Values.db.user | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: pgpassword
                  name: post-delete-secrets
{{ end}}
