apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: eks-http
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik
      namespace: ingress
      sectionName: web
      kind: Gateway

  hostnames:
    - {{ include "fullHostname" . }}

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: eks-https
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik
      sectionName: websecure
      namespace: ingress
      kind: Gateway

  hostnames:
    - {{ include "fullHostname" . }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: auth

      backendRefs:
        - name: eks
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: {{ .Release.Namespace }}
spec:
  chain:
    middlewares:
      - name: auth-error-redirection
        namespace: ingress
      - name: test-auth
        namespace: ingress
