apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: eks
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ include "fullHostname" . }}`)
      kind: Rule
      middlewares:
        - name: auth-error-redirection
          namespace: ingress
        - name: test-auth
          namespace: ingress
      services:
        - name: eks
          port: http
    - match: Host(`{{ include "fullHostname" . }}`) && (PathPrefix(`/lookup`) || PathPrefix(`/suggest`))
      kind: Rule
      middlewares:
        - name: auth-error-redirection
          namespace: ingress
        - name: test-auth
          namespace: ingress
      services:
        - name: bag-lookup
          port: http
  # This falls back to the default certificate, which should be a wildcard cert for *.eks-test.nl
  tls: {}
