apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eks-tls-cert
  namespace: test-env
spec:
  secretName: eks-tls-cert
  issuerRef:
    name: letsencrypt-production-http
    kind: ClusterIssuer
  dnsNames:
    - {{ include "fullHostname" . | quote }}
