apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks
  namespace: {{ .Release.Namespace }}
  annotations:
    # TODO move to production
    cert-manager.io/cluster-issuer: letsencrypt-staging-http
spec:
  ingressClassName: traefik
  rules:
    - host: {{ include "fullHostname" . | quote }}
      http:
        paths:
          - backend:
              service:
                name: eks
                port:
                  name: http
            pathType: Prefix
            path: "/"

  tls:
    - hosts:
        - {{ include "fullHostname" . | quote }}
      secretName: eks-tls-cert
