{{ if .Values.db.runMigrations }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
  labels:
    app.kubernetes.io/name: migrate-db
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: test-deployment
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: migrate-db
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: test-deployment
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: migrate-db
          image: "ghcr.io/kiesraad/e-ks/apply_fixtures:{{ .Chart.AppVersion }}"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database_url
                  name: pre-install-secrets
{{ end }}
