apiVersion: v1
kind: Service
metadata:
  name: eks
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: eks
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
