{{ if .Values.db.setup }}
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-database-hook
  labels:
    app.kubernetes.io/name: setup-db
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: test-deployment
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: setup-db
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: test-deployment
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: setup-db
          image: "ghcr.io/kiesraad/e-ks/db:{{ .Chart.AppVersion }}"
          command:
            - createdb
            - {{ .Values.subdomain }}
          env:
            - name: PGHOST
              value: {{ .Values.db.host | quote }}
            - name: PGPORT
              value: {{ .Values.db.port | quote }}
            - name: PGUSER
              value: {{ .Values.db.user | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: pgpassword
                  name: helm-hook-secrets
{{ end }}
