name: Codecov

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  TZ: "Europe/Amsterdam"

jobs:
  codecov:
    name: Check code coverage
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      SQLX_OFFLINE: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      # Branch coverage requires Rust nightly: https://github.com/taiki-e/cargo-llvm-cov/issues/8
      - name: Setup Rust Nightly
        shell: bash
        run: >
          rustup update nightly &&
          rustup default nightly
      - name: Cargo cache
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov
      - name: Install Nextest
        run: cargo install cargo-nextest
      - name: Setup project
        run: cargo run --bin setup
      - name: Run tests with coverage
        run: cargo llvm-cov nextest --branch --profile ci
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Nextest Results
          files: target/nextest/ci/junit.xml
          disable_search: true
          fail_ci_if_error: true
      - name: Create code coverage report
        run: cargo llvm-cov report --cobertura --output-path ./target/llvm-cov-target/codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Nextest Coverage
          files: target/llvm-cov-target/codecov.json
          disable_search: true
          fail_ci_if_error: true
      - name: Report disk space
        run: df -h
